name: my_first_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  vibration: ^1.8.4
  side_rail: ^0.0.5
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  hyper_effects: ^0.2.3
  super_tooltip: ^2.0.7
  url_launcher: ^6.2.5
  dart_openai: ^5.1.0
  get_storage: ^2.1.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  sp_util: ^2.0.3
  speech_to_text: ^6.6.0
  lottie: ^3.1.0
  provider: ^6.1.2
  flutter_easyloading: ^3.0.5
  flutter_markdown: ^0.6.22+1
  share_plus: ^8.0.2
  flutter_tts: ^4.0.2
  animated_text_kit: ^4.2.2
  custom_button_builder: ^0.0.4
  
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-Regular.ttf

